<?php

/**
 * Implements hook_perm().
 */
function oa_perm() {
  return array('OA - Review files', 'OA - Access assignment webforms');
}

/**
 * Implements hook_menu().
 */
function oa_menu() {
  $items = array();
  $items['file-review'] = array(
    'page callback' => 'oa_filereview',
    'access arguments' => array('OA - Review files'),
    'title' => 'Applicant File Review',
  );
  $items['assignment-webform/%'] = array(
    'page callback' => 'oa_webform',
    'page arguments' => array(1),
    'access arguments' => array('OA - Access assignment webforms'),
    'title' => 'On Assignment Webform',
  );
  $items['oa/createpdfform'] = array(
    'page callback' => 'oa_createpdfform',
    'access arguments' => array('OA - Access assignment webforms'),
  );

  return $items;
}

/**
 * On Assignment File Review
 * /file-review
 */
function oa_filereview() {
  global $user;
  $account = $user;
  profile_load_profile($account);
  $rmaxid = $account->profile_rmaxid;
  
  drupal_add_css(drupal_get_path('module', 'oa_ucm_jquery_plugin') .'/jquery-ui.css');
  drupal_add_css(drupal_get_path('module', 'oa_ucm_jquery_plugin') .'/TableTools.css');
  drupal_add_css(drupal_get_path('module', 'oa_ucm_jquery_plugin') .'/TableTools_JUI.css');
  drupal_add_css(drupal_get_path('module', 'oa_ucm_jquery_plugin') .'/demo_table.css');
  drupal_add_css(drupal_get_path('module', 'oa_ucm_jquery_plugin') .'/applicantfilereview.css');

  jquery_plugin_add_fullname('jquery.1.6.min');
  jquery_plugin_add_fullname('jquery-ui-1.8.13.custom.min');
  jquery_plugin_add('dataTables');
  jquery_plugin_add_fullname('jquery.dataTables.rowGrouping');
  jquery_plugin_add_fullname('jquery.dataTables.rowGrouping.custom');
  jquery_plugin_add_fullname('TableTools.min');
  jquery_plugin_add_fullname('jquery.simplemodal-1.4.1.min');

  $headers = array(
    'rmaxid' => $rmaxid,
    'cmplid' => $_POST["modalityId"] ? $_POST["modalityId"] : 'ShowAll',
  ); 

  $response = drupal_http_request('http://localhost/OAApplicantEfile/retrieveApplicantEfilePage', $headers, 'POST');
  return $response->data;
}

/**
 * On Assignment Webform
 * assignment-webform/%
 */
function oa_webform($form_name) {
  global $user;
  $account = $user;
  profile_load_profile($account);
  $rmaxid = $account->profile_rmaxid;

  drupal_add_css(drupal_get_path('module', 'oa_ucm_jquery_plugin') .'/applicantwebform.css');

  if (is_null($form_name) || is_null($rmaxid)) {
    return 'Must supply formid and have a valid rmaxid.';
  }
  $headers = array(
    'rmaxid' => $rmaxid,
    'webformName' => $form_name
  );

  $response = drupal_http_request('http://localhost/OAApplicantEfile/' . $form_name . '.jsp', $headers, 'POST');
  return $response->data;
}

/**
 * Passthrough callback for proxying data to/from Tomcat
 */
function oa_createpdfform() {
  global $user;
  $account = $user;
  profile_load_profile($account);

  $headers = array(
    'rmaxid' => $account->profile_rmaxid,
    'webformName' => $_POST['webformName'],
    'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8',
  );
  
  // Given input parameters (form submission, url arguments, etc)
  $data = $_POST;
  
  // Proxy to Tomcat
  $response = drupal_http_request('http://172.23.8.56/OAApplicantEfile/CreatePDFForm', $headers, 'POST', http_build_query($data, '', '&'));

  // Set response headers
  foreach (array('Date', 'Server', 'Content-Disposition', 'Content-Type') AS $k) {
    drupal_set_header($k . ': ' . $response->headers[$k]);
  }
  print $response->data;
  exit();
}



function wddsm($obj, $msg = NULL) {
  if (function_exists('dsm')) {
    dsm($obj, $msg);
  }
  else {
    watchdog('rp-' . $msg, '<pre>'. print_r($obj, TRUE) .'</pre>');
  }
}
