<?php

/**
 * Implements hook_perm().
 */
function oa_services_perm() {
  return array(
    'account resource create an account',
    'account resource view any account',
    'account resource update any note',
    'account resource delete any note',
    'message resource create an message',
  );
}

/**
 * Implementation of hook_services_resources().
 */
function oa_services_services_resources() {
  return array(
    'account' => array(
      'create' => array(
        'help' => 'Creates a account',
        'file' => array('file' => 'inc', 'module' => 'oa_services'),
        'callback' => '_accountresource_create',
        'access arguments' => array('account resource create an account'),
        'access arguments append' => FALSE,
        'args' => array(
          array(
            'name' => 'data',
            'type' => 'struct',
            'description' => 'The account data array.',
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
      'retrieve' => array(
        'help' => 'Retrieves an account',
        'file' => array('file' => 'inc', 'module' => 'oa_services'),
        'callback' => '_accountresource_retrieve',
        'access arguments' => array('account resource view any account'),
        'access arguments append' => FALSE,
        'args' => array(
          array(
            'name' => 'rmaxid',
            'type' => 'int',
            'description' => 'The rmaxid of the account to get.',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
        ),
      ),
      'update' => array(
        'help' => 'Updates an account',
        'file' => array('file' => 'inc', 'module' => 'oa_services'),
        'callback' => '_accountresource_update',
        'access arguments' => array('account resource update any account'),
        'access arguments append' => FALSE,
        'args' => array(
          array(
            'name' => 'rmaxid',
            'type' => 'int',
            'description' => 'The rmaxid of the account to update.',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
          array(
            'name' => 'data',
            'type' => 'struct',
            'description' => 'The account data to update. An array of key-value pairs with attributes to update.',
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
    ),

    'message' => array(
      'create' => array(
        'help' => 'Creates a message',
        'file' => array('file' => 'inc', 'module' => 'oa_services'),
        'callback' => '_messageresource_create',
        'access arguments' => array('message resource create an message'),
        'access arguments append' => FALSE,
        'args' => array(
          array(
            'name' => 'data',
            'type' => 'struct',
            'description' => 'The message data array. Must include the following keys: rmaxid, subject, body',
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
    ),
  );
}


/**
 * Gets an account object by rmaxid.
 *
 * @param int $rmaxid
 * @return object $account
 */
function oa_services_account_load($rmaxid) {
  $record = db_fetch_array(db_query("SELECT uid FROM {profile_values} WHERE fid = 1 AND value = %d", $rmaxid));
  $account = user_load($record);
  profile_load_profile($account);
  return $account;
}

/**
 * Gets a message object by msg_id.
 *
 * @param int $msg_id
 * @return object $message
 */
function oa_services_message_load($msg_id) {
  while ($message = db_fetch_object(db_query("SELECT * FROM {ucm_messages} WHERE msg_id = %d LIMIT 1", $msg_id))) {
    return $message;
  }
  return NULL;
}

/**
 * Creates a message record.
 *
 * @param array $data
 * @return object $message
 */
function oa_services_message_create($data) {
  db_query("INSERT INTO {ucm_messages} (rmaxid, subject, body, timestamp, was_read) VALUES (%d, '%s', '%s', %d, %d)",
    $data['rmaxid'], $data['subject'], $data['body'], $data['timestamp'], $data['was_read']);
  return oa_services_message_load(db_last_insert_id('ucm_messages', 'msg_id'));
}
